version: '3'
services:
  at-service:
    build:
      context: ./AT
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  notificacao-service:
    build:
      context: ./NotificacaoService
    ports:
      - "9000:9000"
    depends_on:
      - eureka-server

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"

  gateway:
    build:
      context: ./gateway  # Caminho do projeto Gateway
    ports:
      - "8081:8080"  # Mapeando a porta do Gateway para o host
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
